/*
 *  Copyright 2015 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) ti.targets; 1, 0, 3,0; 12-11-2015 16:22:07; /db/ztree/library/trees/xdctargets/xdctargets-k07/src/ xlibrary

 */

