/*
 *  Copyright 2015 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) ti.targets.arm.elf; 1, 0, 0,0; 12-11-2015 16:22:08; /db/ztree/library/trees/xdctargets/xdctargets-k07/src/ xlibrary

 */

